# Generated by Django 3.1.4 on 2020-12-17 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201211_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('ETE', 'ETE'), ('ME', 'ME'), ('CE', 'CE'), ('CFPE', 'CFPE'), ('MTE', 'MTE'), ('GCE', 'GCE'), ('BMCSE', 'BMCSE'), ('Architecture', 'Architecture')], default='CSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_number',
            field=models.IntegerField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='phoneNumber'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semister',
            field=models.CharField(choices=[('odd', 'odd'), ('even', 'even')], default='odd', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth')], default='first', max_length=20),
        ),
    ]
