# Generated by Django 3.1.4 on 2020-12-17 14:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201217_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
