# Generated by Django 3.1.4 on 2020-12-17 14:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201217_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
