# Generated by Django 3.1.4 on 2020-12-17 14:35

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201217_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_number',
            field=phone_field.models.PhoneField(blank=True, default=0, help_text='Contact phone number', max_length=31),
            preserve_default=False,
        ),
    ]
