# Generated by Django 3.1.4 on 2020-12-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201217_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='p_number',
        ),
    ]
