# Generated by Django 3.1.4 on 2020-12-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_profile_p_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='p_number',
            field=models.CharField(default='01*********', max_length=11),
        ),
    ]
