# Generated by Django 3.1.4 on 2020-12-18 06:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_p_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+8801', max_length=128, region=None),
        ),
    ]
