# Generated by Django 3.1.4 on 2020-12-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201218_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_number',
            field=models.CharField(default='01', max_length=11),
        ),
    ]
