# Generated by Django 3.1.4 on 2020-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20201218_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='./profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
