# Generated by Django 3.1.4 on 2020-12-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201211_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
