# Generated by Django 3.1.4 on 2020-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201218_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='./post/default.jpg', upload_to='post/'),
        ),
    ]
